/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    apiKeys: ApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    articles: Article;
    concerts: Concert;
    'article-categories': ArticleCategory;
    genres: Genre;
    volunteers: Volunteer;
    media: Media;
    icons: Icon;
    faqs: Faq;
    quotes: Quote;
    navigation: Navigation;
    redirects: Redirect;
    users: User;
    apiKeys: ApiKey;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'article-categories': {
      viewArticlesInCategory: 'articles';
    };
    genres: {
      viewArticlesInGenre: 'articles';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    concerts: ConcertsSelect<false> | ConcertsSelect<true>;
    'article-categories': ArticleCategoriesSelect<false> | ArticleCategoriesSelect<true>;
    genres: GenresSelect<false> | GenresSelect<true>;
    volunteers: VolunteersSelect<false> | VolunteersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    icons: IconsSelect<false> | IconsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    quotes: QuotesSelect<false> | QuotesSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    apiKeys: ApiKeysSelect<false> | ApiKeysSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    options: Option;
  };
  globalsSelect: {
    options: OptionsSelect<false> | OptionsSelect<true>;
  };
  locale: 'da' | 'en';
  user:
    | (User & {
        collection: 'users';
      })
    | (ApiKey & {
        collection: 'apiKeys';
      });
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface ApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  /**
   * This is the name of the page, it will only be used in the admin panel. And is not localized.
   */
  name: string;
  /**
   * This title will be used in references and will set the slug.
   */
  title: string;
  layout?: (Hero | Paragraph | TextImage | ArticleSlider | RecentArticles)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  publishStatus: 'draft' | 'pendingApproval' | 'public';
  slug?: string | null;
  slugLock?: boolean | null;
  contentMeta?: {
    featuredImage?: (string | null) | Media;
    excerpt?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Hero".
 */
export interface Hero {
  /**
   * Select up to 5 articles to feature in the hero block.
   */
  featuredArticles?: (string | Article)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: string;
  /**
   * This is the name of the page, it will only be used in the admin panel. And is not localized.
   */
  name: string;
  /**
   * This title will be used in references and will set the slug.
   */
  title: string;
  articleType: 'review' | 'interview' | 'weekly-releases';
  reviewType?: ('concert' | 'album') | null;
  genres?: (string | Genre)[] | null;
  artistName?: string | null;
  categories?: (string | ArticleCategory)[] | null;
  relatedArticles?: (string | Article)[] | null;
  layout?: (Paragraph | ArticleAuthor | RelatedArticles | Playlist)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  publishStatus: 'draft' | 'pendingApproval' | 'public';
  slug?: string | null;
  slugLock?: boolean | null;
  contentMeta?: {
    featuredImage?: (string | null) | Media;
    excerpt?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "genres".
 */
export interface Genre {
  id: string;
  name: string;
  viewArticlesInGenre?: {
    docs?: (string | Article)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "article-categories".
 */
export interface ArticleCategory {
  id: string;
  /**
   * This is the name of the page, it will only be used in the admin panel. And is not localized.
   */
  name: string;
  /**
   * This title will be used in references and will set the slug.
   */
  title: string;
  viewArticlesInCategory?: {
    docs?: (string | Article)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  layout?: Paragraph[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  publishStatus: 'draft' | 'pendingApproval' | 'public';
  slug?: string | null;
  slugLock?: boolean | null;
  contentMeta?: {
    featuredImage?: (string | null) | Media;
    excerpt?: string | null;
  };
  parent?: (string | null) | ArticleCategory;
  breadcrumbs?:
    | {
        doc?: (string | null) | ArticleCategory;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Paragraph".
 */
export interface Paragraph {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'paragraph';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArticleAuthor".
 */
export interface ArticleAuthor {
  author?: (string | null) | Volunteer;
  id?: string | null;
  blockName?: string | null;
  blockType: 'article-author';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "volunteers".
 */
export interface Volunteer {
  id: string;
  name: string;
  displayName?: string | null;
  roleGroup: 'core' | 'regular';
  volunteerRole: 'writer' | 'photographer' | 'social' | 'other';
  customRole?: string | null;
  email?: string | null;
  profilePicture?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RelatedArticles".
 */
export interface RelatedArticles {
  heading?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'related-articles';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Playlist".
 */
export interface Playlist {
  title?: string | null;
  /**
   * Indsæt embed iframe fra Spotify.
   */
  playlistScript?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'playlist';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextImage".
 */
export interface TextImage {
  order: 'image-left' | 'image-right';
  image: string | Media;
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  addLink?: boolean | null;
  link: {
    type: 'reference' | 'custom';
    openNewTab?: boolean | null;
    url?: string | null;
    relation?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'articles';
          value: string | Article;
        } | null)
      | ({
          relationTo: 'article-categories';
          value: string | ArticleCategory;
        } | null);
    label: string;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'text-image';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArticleSlider".
 */
export interface ArticleSlider {
  heading: string;
  cardType?: ('review' | 'interview') | null;
  addLink?: boolean | null;
  link: {
    type: 'reference' | 'custom';
    openNewTab?: boolean | null;
    url?: string | null;
    relation?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'articles';
          value: string | Article;
        } | null)
      | ({
          relationTo: 'article-categories';
          value: string | ArticleCategory;
        } | null);
    label: string;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'article-slider';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RecentArticles".
 */
export interface RecentArticles {
  heading: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'recent-articles';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "concerts".
 */
export interface Concert {
  id: string;
  featuredImage: string | Media;
  artist: string;
  support?: string | null;
  venue: string;
  city: string;
  date: string;
  ticketLink?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "icons".
 */
export interface Icon {
  id: string;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: string;
  question: string;
  answer?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  publishedAt?: string | null;
  publishStatus: 'draft' | 'pendingApproval' | 'public';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes".
 */
export interface Quote {
  id: string;
  quote: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  author?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Setup menus and navigation globally across your site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: string;
  title: string;
  navItems?:
    | {
        link: {
          type: 'reference' | 'custom';
          openNewTab?: boolean | null;
          url?: string | null;
          relation?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'articles';
                value: string | Article;
              } | null)
            | ({
                relationTo: 'article-categories';
                value: string | ArticleCategory;
              } | null);
          label: string;
        };
        addSubMenu?: boolean | null;
        subMenu?:
          | {
              link: {
                type: 'reference' | 'custom';
                openNewTab?: boolean | null;
                url?: string | null;
                relation?:
                  | ({
                      relationTo: 'pages';
                      value: string | Page;
                    } | null)
                  | ({
                      relationTo: 'articles';
                      value: string | Article;
                    } | null)
                  | ({
                      relationTo: 'article-categories';
                      value: string | ArticleCategory;
                    } | null);
                label: string;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  position?: {
    main?: boolean | null;
    secondary?: boolean | null;
    mobile?: boolean | null;
    footer1?: boolean | null;
    footer2?: boolean | null;
    footer3?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  active?: boolean | null;
  redirectType: '301' | '302';
  /**
   * Redirect from should be a relative path. (E.g. "/old-page")
   */
  redirectFrom: string;
  /**
   * The redirect should be to a complete URL. (E.g. "https://www.oak.dk/new-page")
   */
  redirectTo: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "apiKeys".
 */
export interface ApiKey {
  id: string;
  title: string;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'articles';
        value: string | Article;
      } | null)
    | ({
        relationTo: 'concerts';
        value: string | Concert;
      } | null)
    | ({
        relationTo: 'article-categories';
        value: string | ArticleCategory;
      } | null)
    | ({
        relationTo: 'genres';
        value: string | Genre;
      } | null)
    | ({
        relationTo: 'volunteers';
        value: string | Volunteer;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'icons';
        value: string | Icon;
      } | null)
    | ({
        relationTo: 'faqs';
        value: string | Faq;
      } | null)
    | ({
        relationTo: 'quotes';
        value: string | Quote;
      } | null)
    | ({
        relationTo: 'navigation';
        value: string | Navigation;
      } | null)
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'apiKeys';
        value: string | ApiKey;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'apiKeys';
        value: string | ApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'apiKeys';
        value: string | ApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  layout?:
    | T
    | {
        hero?: T | HeroSelect<T>;
        paragraph?: T | ParagraphSelect<T>;
        'text-image'?: T | TextImageSelect<T>;
        'article-slider'?: T | ArticleSliderSelect<T>;
        'recent-articles'?: T | RecentArticlesSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  publishStatus?: T;
  slug?: T;
  slugLock?: T;
  contentMeta?:
    | T
    | {
        featuredImage?: T;
        excerpt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Hero_select".
 */
export interface HeroSelect<T extends boolean = true> {
  featuredArticles?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Paragraph_select".
 */
export interface ParagraphSelect<T extends boolean = true> {
  richText?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextImage_select".
 */
export interface TextImageSelect<T extends boolean = true> {
  order?: T;
  image?: T;
  richText?: T;
  addLink?: T;
  link?:
    | T
    | {
        type?: T;
        openNewTab?: T;
        url?: T;
        relation?: T;
        label?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArticleSlider_select".
 */
export interface ArticleSliderSelect<T extends boolean = true> {
  heading?: T;
  cardType?: T;
  addLink?: T;
  link?:
    | T
    | {
        type?: T;
        openNewTab?: T;
        url?: T;
        relation?: T;
        label?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RecentArticles_select".
 */
export interface RecentArticlesSelect<T extends boolean = true> {
  heading?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  articleType?: T;
  reviewType?: T;
  genres?: T;
  artistName?: T;
  categories?: T;
  relatedArticles?: T;
  layout?:
    | T
    | {
        paragraph?: T | ParagraphSelect<T>;
        'article-author'?: T | ArticleAuthorSelect<T>;
        'related-articles'?: T | RelatedArticlesSelect<T>;
        playlist?: T | PlaylistSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  publishStatus?: T;
  slug?: T;
  slugLock?: T;
  contentMeta?:
    | T
    | {
        featuredImage?: T;
        excerpt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArticleAuthor_select".
 */
export interface ArticleAuthorSelect<T extends boolean = true> {
  author?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RelatedArticles_select".
 */
export interface RelatedArticlesSelect<T extends boolean = true> {
  heading?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Playlist_select".
 */
export interface PlaylistSelect<T extends boolean = true> {
  title?: T;
  playlistScript?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "concerts_select".
 */
export interface ConcertsSelect<T extends boolean = true> {
  featuredImage?: T;
  artist?: T;
  support?: T;
  venue?: T;
  city?: T;
  date?: T;
  ticketLink?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "article-categories_select".
 */
export interface ArticleCategoriesSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  viewArticlesInCategory?: T;
  layout?:
    | T
    | {
        paragraph?: T | ParagraphSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishStatus?: T;
  slug?: T;
  slugLock?: T;
  contentMeta?:
    | T
    | {
        featuredImage?: T;
        excerpt?: T;
      };
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "genres_select".
 */
export interface GenresSelect<T extends boolean = true> {
  name?: T;
  viewArticlesInGenre?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "volunteers_select".
 */
export interface VolunteersSelect<T extends boolean = true> {
  name?: T;
  displayName?: T;
  roleGroup?: T;
  volunteerRole?: T;
  customRole?: T;
  email?: T;
  profilePicture?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "icons_select".
 */
export interface IconsSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  publishedAt?: T;
  publishStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes_select".
 */
export interface QuotesSelect<T extends boolean = true> {
  quote?: T;
  author?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  title?: T;
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              openNewTab?: T;
              url?: T;
              relation?: T;
              label?: T;
            };
        addSubMenu?: T;
        subMenu?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    openNewTab?: T;
                    url?: T;
                    relation?: T;
                    label?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  position?:
    | T
    | {
        main?: T;
        secondary?: T;
        mobile?: T;
        footer1?: T;
        footer2?: T;
        footer3?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  active?: T;
  redirectType?: T;
  redirectFrom?: T;
  redirectTo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "apiKeys_select".
 */
export interface ApiKeysSelect<T extends boolean = true> {
  title?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "options".
 */
export interface Option {
  id: string;
  defaultPages: {
    homepage: string | Page;
  };
  companyDetails?: {
    companyName?: string | null;
    vatNumber?: string | null;
    address?: string | null;
    city?: string | null;
    email?: string | null;
    phone?: string | null;
  };
  socialLinks?:
    | {
        platform?:
          | (
              | 'Facebook'
              | 'LinkedIn'
              | 'YouTube'
              | 'Twitter'
              | 'Instagram'
              | 'TikTok'
              | 'Snapchat'
              | 'Pinterest'
              | 'Reddit'
              | 'Discord'
              | 'Twitch'
              | 'Threads'
              | 'WhatsApp'
              | 'Telegram'
            )
          | null;
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  translations?: {
    tlCopyright?: string | null;
  };
  /**
   * IMPORTANT! Unchecking this will remove the site from all organic listings on Google.
   */
  indexing?: {
    siteIndexable?: boolean | null;
  };
  meta?: {
    metaTitlePrefix?: string | null;
    metaTitleSuffix?: string | null;
    defaultImage?: (string | null) | Media;
  };
  structuredData?: {
    structuredData?: string | null;
  };
  /**
   * Be careful. Scripts have a direct influence on how the site performs. Only edit this page, if you know what you are doing.
   */
  scriptInjection?: {
    headScript?: string | null;
    bodyScript?: string | null;
    footerScript?: string | null;
  };
  linkTypeTemplate: {
    type: 'reference' | 'custom';
    openNewTab?: boolean | null;
    url?: string | null;
    relation?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'articles';
          value: string | Article;
        } | null)
      | ({
          relationTo: 'article-categories';
          value: string | ArticleCategory;
        } | null);
    label: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "options_select".
 */
export interface OptionsSelect<T extends boolean = true> {
  defaultPages?:
    | T
    | {
        homepage?: T;
      };
  companyDetails?:
    | T
    | {
        companyName?: T;
        vatNumber?: T;
        address?: T;
        city?: T;
        email?: T;
        phone?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        link?: T;
        id?: T;
      };
  translations?:
    | T
    | {
        tlCopyright?: T;
      };
  indexing?:
    | T
    | {
        siteIndexable?: T;
      };
  meta?:
    | T
    | {
        metaTitlePrefix?: T;
        metaTitleSuffix?: T;
        defaultImage?: T;
      };
  structuredData?:
    | T
    | {
        structuredData?: T;
      };
  scriptInjection?:
    | T
    | {
        headScript?: T;
        bodyScript?: T;
        footerScript?: T;
      };
  linkTypeTemplate?:
    | T
    | {
        type?: T;
        openNewTab?: T;
        url?: T;
        relation?: T;
        label?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}